### PR TITLE
Upgrade go.mod

### PR DESCRIPTION
**Pull request by plutov**
1. Use the latest Go version
2. Run `go mod tidy` to update the go.mod

### CODE REVIEW

**Comment by iggy** [comment]
I don't actually have any systems that have go 1.19 installable. Can you maybe bump that down to 1.18?

**Comment by plutov** [comment]
@iggy sure, go 1.18 is also quite new, but I thought it's always more secure/faster to use 1.19

**Comment by plutov** [comment]
@iggy I changed to 1.18

**Comment by iggy** [comment]
Thanks for the submission

**Pull request merged**
